# Generated by Django 6.0.2 on 2026-06-17 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SHOP_OWNER', 'Shop Owner'), ('SUPPLIER', 'Supplier'), ('COURIER', 'Courier'), ('MARKETER', 'Marketer')], default='CUSTOMER', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('badge', models.CharField(choices=[('none', 'None'), ('verified', 'Verified'), ('vip', 'VIP'), ('trusted', 'Trusted')], default='none', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('policy', models.FileField(blank=True, null=True, upload_to='policy/')),
                ('bank_account', models.CharField(blank=True, choices=[('COMMERCIAL_BANK_OF_ETHIOPIA', 'Commercial Bank of Ethiopia'), ('COOPERATIVE_BANK_OF_OROMIA', 'Cooperative Bank of Oromia'), ('AWASH_INTERNATIONAL_BANK', 'Awash International Bank'), ('BANK_OF_ABYSSINIA', 'Bank of Abyssinia'), ('DASHEN_BANK', 'Dashen Bank'), ('ENAT_BANK', 'Enat Bank'), ('BUNNA_INTERNATIONAL_BANK', 'Bunna International Bank'), ('NIB_INTERNATIONAL_BANK', 'Nib International Bank'), ('ADDIS_INTERNATIONAL_BANK', 'Addis International Bank'), ('AMHARA_BANK', 'Amhara Bank'), ('LION_INTERNATIONAL_BANK', 'Lion International Bank'), ('DEVELOPMENT_BANK_OF_ETHIOPIA', 'Development Bank of Ethiopia'), ('SIDAMA_BANK', 'Sidama Bank'), ('SIINQEE_BANK', 'Siinqee Bank'), ('TSDEY_BANK', 'Tsedey Bank'), ('TSHAY_BANK', 'Tsehay Bank'), ('HIBRET_BANK', 'Hibret Bank'), ('HIJRA_BANK', 'Hijra Bank'), ('RAMMIS_BANK', 'Rammis Bank'), ('GADAA_BANK', 'Gadaa Bank'), ('NATIONAL_BANK_OF_ETHIOPIA', 'National Bank of Ethiopia')], max_length=50, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('BANK', 'Bank'), ('TELEBIRR', 'Telebirr'), ('MPESA', 'M-Pesa')], max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('shop_owner', 'payment_type')},
            },
        ),
    ]
