# Generated by Django 6.0.2 on 2026-06-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_jobs',
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
