# Generated by Django 6.0.2 on 2026-07-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'address_type')},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('SHIPPING', 'Shipping'), ('BILLING', 'Billing')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='address',
            name='label',
        ),
    ]
