# Generated by Django 6.0.2 on 2026-07-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_address_options_alter_address_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
