# Generated by Django 6.0.2 on 2026-07-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_paymentmethod_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
