# Generated by Django 6.0.2 on 2026-07-15 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_paymentmethod_is_verified'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(blank=True, max_length=500)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pickup_available', models.BooleanField(default=True)),
                ('processing_time', models.CharField(choices=[('SAME_DAY', 'Same day'), ('1_BUSINESS_DAY', '1 business day'), ('2_BUSINESS_DAYS', '2 business days'), ('3_BUSINESS_DAYS', '3 business days')], default='1_BUSINESS_DAY', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_settings', to='shop.shop')),
            ],
        ),
    ]
