# Generated by Django 6.0.2 on 2026-06-17 11:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_gmv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('orders_count', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='shop.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'date'], name='analytics_s_shop_id_19acd8_idx')],
                'unique_together': {('shop', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SupplierDailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('units_sold', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_daily_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', 'date'], name='analytics_s_supplie_6a4571_idx')],
                'unique_together': {('supplier', 'date')},
            },
        ),
    ]
