# Generated by Django 6.0.2 on 2026-07-07 19:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_delete_marketerdailyanalytics'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMonthlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gmv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_start', models.DateField(db_index=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformWeeklyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gmv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(db_index=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformYearlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gmv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_start', models.DateField(db_index=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopMonthlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('orders_count', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_start', models.DateField(db_index=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='shop.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'month_start'], name='analytics_s_shop_id_170001_idx')],
                'unique_together': {('shop', 'month_start')},
            },
        ),
        migrations.CreateModel(
            name='ShopWeeklyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('orders_count', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(db_index=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='shop.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'week_start'], name='analytics_s_shop_id_ded4b0_idx')],
                'unique_together': {('shop', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='ShopYearlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('orders_count', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_start', models.DateField(db_index=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='shop.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'year_start'], name='analytics_s_shop_id_9bb1eb_idx')],
                'unique_together': {('shop', 'year_start')},
            },
        ),
        migrations.CreateModel(
            name='SupplierMonthlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('units_sold', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_start', models.DateField(db_index=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', 'month_start'], name='analytics_s_supplie_f953bc_idx')],
                'unique_together': {('supplier', 'month_start')},
            },
        ),
        migrations.CreateModel(
            name='SupplierWeeklyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('units_sold', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(db_index=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', 'week_start'], name='analytics_s_supplie_e7ceac_idx')],
                'unique_together': {('supplier', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='SupplierYearlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('units_sold', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_start', models.DateField(db_index=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', 'year_start'], name='analytics_s_supplie_c637d9_idx')],
                'unique_together': {('supplier', 'year_start')},
            },
        ),
    ]
