# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooklog",
            name="event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webhooklog",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="webhooklog",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="webhooklog",
            constraint=models.UniqueConstraint(
                condition=models.Q(event_id__isnull=False),
                fields=("provider", "event_id"),
                name="uniq_payment_webhook_provider_event_id",
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(fields=["provider", "event_id"], name="payment_web_provide_d55a26_idx"),
        ),
    ]
