# Generated by Django 5.1.6 on 2026-06-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_earnings_payouts_hardening"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="earning",
            new_name="payment_ear_user_id_b96175_idx",
            old_name="payment_ear_user_id_c4f24a_idx",
        ),
        migrations.RenameIndex(
            model_name="payoutrequest",
            new_name="payment_pay_user_id_0cb7dd_idx",
            old_name="payment_pay_user_id_e1993b_idx",
        ),
        migrations.RenameIndex(
            model_name="webhooklog",
            new_name="payment_web_provide_c5818d_idx",
            old_name="payment_web_provide_d55a26_idx",
        ),
    ]
