# Generated by Django 6.0.2 on 2026-06-17 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('marketer', '0001_initial'),
        ('order', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketercommission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_commissions', to='order.order'),
        ),
        migrations.AddField(
            model_name='marketercommission',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_commissions', to='order.orderitem'),
        ),
        migrations.AddField(
            model_name='marketercommission',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_commissions', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='marketercontract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketer_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketercontract',
            name='marketer',
            field=models.ForeignKey(limit_choices_to={'role': 'MARKETER'}, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketercontract',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_contracts', to='shop.shop'),
        ),
        migrations.AddField(
            model_name='marketercommission',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='marketer.marketercontract'),
        ),
        migrations.AddField(
            model_name='marketercontractproduct',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_products', to='marketer.marketercontract'),
        ),
        migrations.AddField(
            model_name='marketercontractproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_contracts', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='marketercontract',
            index=models.Index(fields=['status'], name='marketer_ma_status_545cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='marketercontract',
            index=models.Index(fields=['start_date', 'end_date'], name='marketer_ma_start_d_370c35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketercontract',
            unique_together={('shop', 'marketer')},
        ),
        migrations.AddIndex(
            model_name='marketercommission',
            index=models.Index(fields=['status'], name='marketer_ma_status_1dde76_idx'),
        ),
        migrations.AddIndex(
            model_name='marketercommission',
            index=models.Index(fields=['contract'], name='marketer_ma_contrac_7a5fad_idx'),
        ),
        migrations.AddIndex(
            model_name='marketercommission',
            index=models.Index(fields=['order'], name='marketer_ma_order_i_54829e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketercommission',
            unique_together={('contract', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='marketercontractproduct',
            index=models.Index(fields=['contract'], name='marketer_ma_contrac_15e883_idx'),
        ),
        migrations.AddIndex(
            model_name='marketercontractproduct',
            index=models.Index(fields=['product'], name='marketer_ma_product_3d7240_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketercontractproduct',
            unique_together={('contract', 'product')},
        ),
    ]
