# Generated by Django 5.1.6 on 2026-02-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = []
