# Generated by Django 5.1.6 on 2026-08-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_add_source_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="source_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_variants",
                to="catalog.productvariant",
            ),
        ),
    ]
