# Generated by Django 6.0.2 on 2026-06-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courier', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='order.order'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='courier_shi_status_61b857_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['courier', 'status'], name='courier_shi_courier_becbaa_idx'),
        ),
    ]
