# Generated by Django 5.1.6 on 2026-02-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0002_initial"),
    ]

    operations = []
