# Generated by Django 5.1.6 on 2026-03-27 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courier",
            "0002_rename_courier_shi_status_03d7de_idx_courier_shi_status_61b857_idx_and_more",
        ),
        ("order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
