# Generated by Django 5.1.6 on 2026-03-22 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_follow"),
    ]

    operations = []
